Cla terms policy
mercedes-benz/foss pull request #68
Opened 2024-12-05 09:06 UTC by AnishaM7

2024-12-06 11:50 UTC, schr3gl3j requested changes

2024-12-06 11:50 UTC, schr3gl3j commented on cla/CLA_BOT_PRIVACY_POLICY.md
> +### Contributor License Agreement with Mercedes-Benz Tech Innovation GmbH Wilhelm-Runge-Straße 11 89081 Ulm
Could you please rename this file? CLA_BOT_PRIVACY_POLICY implies, that we are talking about a privacy policy, but the document contains the CLA of Mercedes-Benz Tech Innovation. This should be reflected in the filename.

2024-12-06 11:50 UTC, schr3gl3j commented on cla/CLA_BOT_PRIVACY_POLICY.md
Please rename the file and add mbti so we avoid confusions for other FOSS Cos

2024-12-13 04:55 UTC, AnishaM7 commented on cla/CLA_BOT_PRIVACY_POLICY.md
Hi @schr3gl3j, we have updated the file name to ```CLA_BOT_MBTI.md```, please check now.

2024-12-13 12:07 UTC, schr3gl3j approved these changes

2025-01-07 08:09 UTC, ogruene requested changes
Please see my suggestion containing a small change. Except this, it looks good to me.

2025-01-07 08:09 UTC, ogruene commented on cla/CLA_BOT_MBTI.md
> +### Contributor License Agreement with Mercedes-Benz Tech Innovation GmbH Wilhelm-Runge-Straße 11 89081 Ulm
```suggestion
### Contributor License Agreement with Mercedes-Benz Tech Innovation GmbH, Wilhelm-Runge-Straße 11, 89081 Ulm
```

2025-02-13 13:19 UTC, ogruene approved these changes
Looks good.

2025-02-13 13:20 UTC, merged